# Generated by Django 4.2 on 2024-04-18 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_or_birthday',
            new_name='date_of_birth',
        ),
    ]
